name: Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[nobuild]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: MAVEN_USER
          server-password: GITHUB_TOKEN
      - name: Get version
        run: 'echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV'
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ env.VERSION }}-${{ github.run_number }}
      - name: Publish
        run: 'mvn -B deploy -pl opengl -Dmaven.wagon.http.pool=false --no-transfer-progress'
        env:
          MAVEN_USER: 'Redstonecrafter0'
          GITHUB_TOKEN: ${{ secrets.MAVEN_DEPLOY }}
  dokka:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Dokka Build
        run: 'maven pre-site'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./opengl/target/dokka
          publish_branch: gh-pages
          destination_dir: ./dokka
  qodana:
    runs-on: ubuntu-latest
    needs:
      - dokka
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          linter: jetbrains/qodana-jvm
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          publish_branch: gh-pages
          destination_dir: ./qodana
